### ISSUE TITLE
Duplication of import rows

### ISSUE THREAD

**Issue by homoky** [bf-software/import-helper#1]
Hi @bf-software ,

Petr from [Steady Cursor](https://steadycursor.com) here.

I love the extension and it's concept. It is 100 % something that is missing in VS Code by default. I hate jumping in text to get import right.

I've installed the extension today and I for some reason it does not fill out the import in one step and it makes duplicates.

https://github.com/user-attachments/assets/5cb8a482-a890-4294-aa59-f21638afe251

Cheers,
Petr

**Comment by bf-software** [comment]
Hi Petr,

Thanks for that video, it's super helpful.  I just have a couple of questions:

1) what extension you are using that is adding the error messages in the code area? 
    (the red messages like: $${\color{red}\textsf{Cannot find module '' or its corresponding type declarations.}}$$)
    
2) is the vscode the latest version, running on a mac? and is it running directly on the Mac itself, or inside of a virtual machine?

Thanks,
Bill.

**Comment by homoky** [comment]
Hey!

Thanks for fast reply!

1. Plugin is called [Error lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens), it is must have! 
2. It is latest VSCode Insiders, plugin is latest version and it is not run on Mac directly, I use Github Codespaces

Hope that helps

**Comment by bf-software** [comment]
Hi Petr,

Looks like I found the problem: Import Helper wasn't working correctly when "Auto Save" was being used in vscode. (I don't use that feature.)  I've released v1.2.1 which fixes it.

Let me know if you have any other issues, and thanks for the info!
-Bill.
